builds:
  - binary: tldr
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

archives:
  -
    wrap_in_directory: true
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x64
      386: x86
      darwin: macos
    files:
      - LICENSE
      - LICENSE-tldr-pages

brews:
  -
    github:
      owner: 4d63
      name: homebrew-tap
    folder: Formula
    homepage: "https://4d63.com/tldr"
    description: Simplified and community-driven man pages (tldr-pages).
    test: |
      system "#{bin}/tldr -version"
    install: |
      bin.install "tldr"
